import jsPDF from 'jspdf';

type PdfRow = { label: string; value: string };

type PdfPayload = {
  title: string;
  inputs: PdfRow[];
  summary: PdfRow[];
  chartImage?: string;
  schedule?: PdfRow[];
};

type DashboardPdfPayload = {
  title: string;
  filters: PdfRow[];
  kpis: PdfRow[];
  charts?: {
    trend?: string;
    comparison?: string;
    distribution?: string;
  };
  requests?: { label: string; value: string }[];
};

export const downloadCalculatorPdf = ({ title, inputs, summary, chartImage, schedule }: PdfPayload): void => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  let cursorY = 50;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('RupeePlanner Report', marginX, cursorY);
  cursorY += 24;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Calculator: ${title}`, marginX, cursorY);
  cursorY += 26;

  doc.setFont('helvetica', 'bold');
  doc.text('Inputs', marginX, cursorY);
  cursorY += 16;
  doc.setFont('helvetica', 'normal');

  inputs.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
    cursorY += 16;
  });

  cursorY += 8;
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', marginX, cursorY);
  cursorY += 16;
  doc.setFont('helvetica', 'normal');

  summary.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
    cursorY += 16;
  });

  if (schedule && schedule.length > 0) {
    cursorY += 8;
    doc.setFont('helvetica', 'bold');
    doc.text('Schedule', marginX, cursorY);
    cursorY += 16;
    doc.setFont('helvetica', 'normal');
    schedule.slice(0, 12).forEach((row) => {
      doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
      cursorY += 14;
    });
  }

  if (chartImage) {
    cursorY += 12;
    doc.setFont('helvetica', 'bold');
    doc.text('Chart Snapshot', marginX, cursorY);
    cursorY += 12;

    doc.addImage(chartImage, 'PNG', marginX, cursorY, 520, 260, undefined, 'FAST');
  }

  doc.setFontSize(10);
  doc.setTextColor('#6b7280');
  doc.text('Generated by RupeePlanner.in', marginX, 800);

  doc.save(`rupeeplanner-${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
};

export const downloadDashboardPdf = ({ title, filters, kpis, charts, requests }: DashboardPdfPayload): void => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  const pageHeight = 842;
  let cursorY = 50;

  const ensureSpace = (height: number) => {
    if (cursorY + height > pageHeight - 60) {
      doc.addPage();
      cursorY = 50;
    }
  };

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('RupeePlanner Dashboard Report', marginX, cursorY);
  cursorY += 24;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Report: ${title}`, marginX, cursorY);
  cursorY += 18;
  doc.setFontSize(10);
  doc.setTextColor('#6b7280');
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, marginX, cursorY);
  doc.setTextColor('#111827');
  cursorY += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Filters', marginX, cursorY);
  cursorY += 16;
  doc.setFont('helvetica', 'normal');
  filters.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
    cursorY += 14;
  });

  cursorY += 10;
  doc.setFont('helvetica', 'bold');
  doc.text('Key Metrics', marginX, cursorY);
  cursorY += 16;
  doc.setFont('helvetica', 'normal');
  kpis.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
    cursorY += 14;
  });

  if (charts?.trend) {
    ensureSpace(300);
    cursorY += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Revenue vs Expenses', marginX, cursorY);
    cursorY += 10;
    doc.addImage(charts.trend, 'PNG', marginX, cursorY, 520, 240, undefined, 'FAST');
    cursorY += 250;
  }

  if (charts?.comparison) {
    ensureSpace(260);
    cursorY += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Department Performance', marginX, cursorY);
    cursorY += 10;
    doc.addImage(charts.comparison, 'PNG', marginX, cursorY, 520, 220, undefined, 'FAST');
    cursorY += 230;
  }

  if (charts?.distribution) {
    ensureSpace(260);
    cursorY += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Category Distribution', marginX, cursorY);
    cursorY += 10;
    doc.addImage(charts.distribution, 'PNG', marginX, cursorY, 420, 220, undefined, 'FAST');
    cursorY += 230;
  }

  if (requests && requests.length > 0) {
    ensureSpace(140);
    cursorY += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Recent Requests', marginX, cursorY);
    cursorY += 16;
    doc.setFont('helvetica', 'normal');
    requests.slice(0, 6).forEach((row) => {
      doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
      cursorY += 14;
    });
  }

  doc.setFontSize(10);
  doc.setTextColor('#6b7280');
  doc.text('Generated by RupeePlanner.in', marginX, pageHeight - 40);

  doc.save(`rupeeplanner-dashboard-${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
};
