import jsPDF from 'jspdf';

type PdfRow = { label: string; value: string };

type PdfPayload = {
  title: string;
  inputs: PdfRow[];
  summary: PdfRow[];
  chartImage?: string;
};

export const downloadCalculatorPdf = ({ title, inputs, summary, chartImage }: PdfPayload): void => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  let cursorY = 50;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('RupeePlanner Report', marginX, cursorY);
  cursorY += 24;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Calculator: ${title}`, marginX, cursorY);
  cursorY += 26;

  doc.setFont('helvetica', 'bold');
  doc.text('Inputs', marginX, cursorY);
  cursorY += 16;
  doc.setFont('helvetica', 'normal');

  inputs.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
    cursorY += 16;
  });

  cursorY += 8;
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', marginX, cursorY);
  cursorY += 16;
  doc.setFont('helvetica', 'normal');

  summary.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, marginX, cursorY);
    cursorY += 16;
  });

  if (chartImage) {
    cursorY += 12;
    doc.setFont('helvetica', 'bold');
    doc.text('Chart Snapshot', marginX, cursorY);
    cursorY += 12;

    doc.addImage(chartImage, 'PNG', marginX, cursorY, 520, 260, undefined, 'FAST');
  }

  doc.setFontSize(10);
  doc.setTextColor('#6b7280');
  doc.text('Generated by RupeePlanner.in', marginX, 800);

  doc.save(`rupeeplanner-${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
};
